@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/RDF-TrineX-Serializer-MockTurtleSoup/project>
	deps:runtime-requirement         [ deps:on "RDF::Prefixes 0.003"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "RDF::Trine 1.000"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Sort::Key 0"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "match::smart"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "JSON 2.00"^^deps:CpanId ].

